In [ ]:
import requests
import requests_cache
from heuristic_clustering import HeuristicClustering
from get_address_info import GetAddressInfo
import datetime
import pymysql
import pandas as pd
import os

In [2]:
data = pd.read_csv("test.csv")
data.head()

,id,address,location,btc_format,num_txs,last_txs,entity,timezone,offsset,arkham_entity,arkham_label,order_id
0,367661,14mp3x1GVCrZgRqbDCAyUJdFjru7K4sZoc,AZ,Valid Format,7883,2016-03-29,Entity 0,Asia/Baku,4.0,NaN,NaN,0
1,2442712,1NekBxxvVPjMDYZ2DQYHuWffW51pfQGDq7,China,Valid Format,7541,2024-12-17,Entity 1,Asia/Shanghai,8.0,NaN,NaN,1
2,639470,1ART8MzPqABmqWz4SsaKLZfrwb9HjNF5dv,Netherlands,Valid Format,6755,2016-05-02,Entity 2,Europe/Amsterdam,1.0,NaN,NaN,2
3,110907,1B9x2xeyzU7X2m6oqhftFPMmhjQdZvFZt1,taiwan,Valid Format,6081,2013-08-29,Entity 3,Asia/Taipei,8.0,NaN,Miner,3
4,154469,19SrA28QN8Eopd7oEWAtmy7dTm2CG7Wuck,PAKISTAN,Valid Format,5349,2024-03-23,Entity 4,Asia/Karachi,5.0,NaN,NaN,4

In [ ]:
def data_write(chunk_size, batch_blockchain_data, batch_tx_inputs, batch_tx_outputs, batch_entities_heur):
    conn = pymysql.connect(
    host = '127.0.0.1',
    user = 'root',
    password =  os.getenv("PASSWORD_MY_SQL"),
    database = 'data'
    )
    while batch_blockchain_data:
        with conn.cursor() as cursor:
            chunk = batch_blockchain_data[:chunk_size]
            sql = "INSERT IGNORE INTO blockchain_data (txid, num_inputs, num_outputs, fee, mempool_entry_time, block_height) VALUES (%s, %s, %s, %s, %s, %s)"
            cursor.executemany(sql, chunk)
            batch_blockchain_data = batch_blockchain_data[chunk_size:]
            conn.commit()

        
    while batch_tx_inputs:
        with conn.cursor() as cursor:
            chunk = batch_tx_inputs[:chunk_size]
            sql = "INSERT IGNORE INTO tx_inputs (txid, input_order, address, value) VALUES (%s, %s, %s, %s)"
            cursor.executemany(sql, chunk)
            batch_tx_inputs = batch_tx_inputs[chunk_size:]
            conn.commit()

    while batch_tx_outputs:
        with conn.cursor() as cursor:
            chunk = batch_tx_outputs[:chunk_size]
            sql = "INSERT IGNORE INTO tx_outputs (txid, output_order, address, value) VALUES (%s, %s, %s, %s)"
            cursor.executemany(sql, chunk)
            batch_tx_outputs = batch_tx_outputs[chunk_size:]
            conn.commit()
    
    while batch_entities_heur:
        with conn.cursor() as cursor:
            chunk = batch_entities_heur[:chunk_size]
            sql = "INSERT IGNORE INTO entities_heur (entity, address) VALUES (%s, %s)"
            cursor.executemany(sql, chunk)
            batch_entities_heur = batch_entities_heur[chunk_size:]
            conn.commit()

In [4]:
path = r"/home/matej/btc_timezone_analysis/data_collection/Webshare_100_proxies.txt"
proxies_dict_list = []

# Open the text file containing the proxies in read mode with UTF-8 encoding
with open(path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        
        # split the TXT format IP:PORT:USER:PASS
        ip, port, user, pwd = line.split(":")
        
        # create a dict directly for requests
        proxy_dict = {
            "http": f"http://{user}:{pwd}@{ip}:{port}",
            "https": f"http://{user}:{pwd}@{ip}:{port}"
        }

        proxies_dict_list.append(proxy_dict)

In [5]:
session = requests_cache.CachedSession('api_cache', expire_after=datetime.timedelta(days=30))

In [17]:
list_to_do = [4211, 4217, 4378, 4472, 4498, 4652, 4730, 4996, 5013, 5080]

In [18]:
a = 50
for index, row in data.iterrows():
    if index in list_to_do:
        print(index)
        address = row["address"]
        entity = row["entity"]
        heur = HeuristicClustering(address, session, a, proxies_dict_list)
        heur.heuristic_clus()
        a = heur.a
        addresses_heur = [[entity,addr] for addr in heur.old_addresses]

        data_write(1000, heur.blockchain_final_data, heur.inputs_final_data, heur.outputs_final_data, addresses_heur)
        print(f"Address {address} written with {len(heur.old_addresses)}")

4211
['17EFZ829NBT2WETLj3wJ5YUfXVaGckuUgs']

:

In [7]:
address = "1Evg5EEKjbqS7bNKnz6kKi4wY3UmDBApFn"
a = 0
address_analysis = GetAddressInfo(address, session, a, proxies_dict_list)
address_analysis.fetch_and_extract()
#heur = HeuristicClustering(address, session, a, proxies_dict_list)
#heur.heuristic_clus()

0.1431427001953125

In [6]:
len(address_analysis.batch_blockchain_data)

804

In [7]:
address_analysis.batch_blockchain_data

[['9d1cb741947cc2e1e512e395e865e266ed394b0a8db654d3717d362f45025f2a',
  29,
  1,
  54.11506953705468,
  '2017-06-09 06:32:45',
  470477],
 ['648d6068b6d18e52323990f34d3b4ffb6243f4098e4e776a0617460ce97adf16',
  1,
  2,
  20.164444444444445,
  '2015-12-07 14:55:46',
  387168],
 ['68305694b87d5175d924b811b6f3d3d0d709da3a4e5d967b6ab68a083c6ca38a',
  2,
  2,
  20.12064343163539,
  '2015-12-06 15:20:01',
  387021],
 ['3bef9c743d158ff2a0867faf89a2bd3a69afbcf955eeceabc5d48d529dc901ed',
  2,
  2,
  20.072386058981234,
  '2015-12-02 15:55:05',
  386396],
 ['a04a87f0c8f4272a582441efd9a39747fec6f181f3c4efa0ae7ec7ea04b6dfbe',
  2,
  2,
  20.0455764075067,
  '2015-11-30 14:45:39',
  386050],
 ['db3f7021a37002c4415a930ecbfa5b83633b22e4851c511cfff0eb7a919e5cd1',
  1,
  2,
  32.94690265486726,
  '2015-11-26 15:06:18',
  385452],
 ['531fd0ffa9d1f525e5319b5be27f7d327d7281f8d959d6f4b6a921cedb0fc4ab',
  2,
  2,
  18.74331550802139,
  '2015-11-25 15:07:47',
  385293],
 ['eb0dfd2b893c2cc84f22adeea1f6971248df646602c92b148e420a6505532edf',
  2,
  2,
  18.718498659517426,
  '2015-11-22 14:26:47',
  384816],
 ['25a014d048bb7adcd78ae0c3c4575c62b997e783f1b5709de853c27bcf8acf1a',
  3,
  2,
  19.863723608445298,
  '2015-11-20 15:11:29',
  384476],
 ['2dbd2e05f59bedaeaea9df4d0c9620d9d426455a8f428581258553c84aeab3d5',
  1,
  2,
  16.74222222222222,
  '2015-11-18 14:30:23',
  384161],
 ['6a2a44268f398c4fabee1ad508f2c14143a4d27e0918577a37d4558408d0ebc3',
  2,
  2,
  21.056300268096514,
  '2015-11-13 13:59:02',
  383386],
 ['1840701341c1a0a90e0a6bf3d8eaea9e8befa0b7daf0bcc5013944b88d4ec19b',
  1,
  2,
  18.786666666666665,
  '2015-11-12 14:21:45',
  383222],
 ['f55e8cb383ba7ed1db70ac3f7102992df34eaae4709ef618816376a65e5ab5cc',
  1,
  2,
  20.004444444444445,
  '2015-11-07 17:04:00',
  382487],
 ['00f075c2fed983e8874867ffbceaed9f546a8a37b7441f6e3935b838fd520ff4',
  1,
  2,
  19.946666666666665,
  '2015-11-05 14:32:12',
  382168],
 ['fc7fa95de128fa985a181be731711df344730c1c92931d8b1a3c081f71541141',
  1,
  2,
  15.15929203539823,
  '2015-11-02 13:52:21',
  381706],
 ['d87f15526608f646b704add96b77e67e88ee1516176413904fbe9736a325ff69',
  1,
  2,
  15.213333333333333,
  '2015-11-01 15:41:17',
  381575],
 ['39cde104aa6591fd51e312ffe013d6da944eeebee75f7366753f3774f4f4fad0',
  2,
  2,
  15.184986595174262,
  '2015-10-30 14:13:03',
  381246],
 ['1bb7ba75b00eda0bbe96079568b055722fb1d53646323784ee7d36491332c03b',
  3,
  2,
  15.132947976878613,
  '2015-10-29 14:39:17',
  381086],
 ['0c83acb42ec5c1de98e5d484bd6af5d18c9a8393ad6429a90cf131494446e37f',
  1,
  2,
  13.699115044247788,
  '2015-10-28 16:00:13',
  380953],
 ['d25f1619b327d34d4ec032fe5750656b5bd4a92670a05219593975671b9e1c06',
  1,
  2,
  16.48,
  '2015-10-22 14:54:42',
  380055],
 ['4ec01a7e86e3ebe4dbf9856708eb80efea1b9627f7c2ddc8868412f4b447eea6',
  1,
  2,
  16.371681415929203,
  '2015-10-21 15:15:13',
  379900],
 ['247c75efb2084e4cadb435be2dc5d692fdfe6532d704e6b4b7530abb55590c32',
  2,
  2,
  13.632707774798927,
  '2015-10-20 14:30:18',
  379755],
 ['a8b010e69b8f405dc79a9569e0dae32668eba9e4234901d90549b5c8a6c19803',
  2,
  2,
  13.615591397849462,
  '2015-10-16 13:45:22',
  379175],
 ['449bbc2e3303e3c74bd5004fac0b0aa2cdd179c385b6d2c3b54ae04ca7eab794',
  2,
  2,
  13.554959785522788,
  '2015-10-13 14:27:19',
  378708],
 ['0add592c5b4a00c86ec2ea4f3ce68613da008782e566003e5c595f4c2d8e6089',
  1,
  2,
  27.333333333333332,
  '2015-10-08 13:54:24',
  378003],
 ['50ce96b0a6f2e08c942d27d3d7c826f9d71dd9f2ee81d156691377eaeba71742',
  2,
  2,
  11.579088471849866,
  '2015-09-28 15:29:18',
  376530],
 ['30d9bdbf7f8274c1156095a42d2afea931723f7060701fde7b7841589b8f73b5',
  2,
  2,
  12.576407506702413,
  '2015-09-24 12:52:36',
  375913],
 ['35bb8b50854ff317e28cde6bf1da4fb30723614ef84ea1216367b58ba683d339',
  1,
  2,
  12.613333333333333,
  '2015-09-22 12:29:32',
  375616],
 ['6b024d4687d70200ff182ea76ba5073e94d50ab4f86dd75c62dbe2c050c4af45',
  2,
  2,
  11.613941018766756,
  '2015-09-21 13:33:58',
  375471],
 ['9480a8e6ab8631a77c85475cd796ab0a7ce13f5d430d26c16c10b5d62d61104e',
  8,
  2,
  13.21003963011889,
  '2015-09-18 06:00:05',
  375035],
 ['d22cf35d7553a4a38cdb516c816a880873d89b9fb30f09c1b695fb3277682ef5',
  1,
  2,
  12.553097345132743,
  '2015-09-12 13:27:12',
  374189],
 ['a368719247eed7459713dac55411ebc50fc6ba6fa7ae13868e2048db6ab881ca',
  1,
  2,
  13.63111111111111,
  '2015-09-08 12:58:54',
  373566],
 ['2ee7bd173a030ed774bf0b775b2b420aa2b4aea506f6ea6679880824c86132bb',
  1,
  2,
  15.0929203539823,
  '2015-09-02 20:27:19',
  372729],
 ['bb8f0428e5c1a1300e0f376db210c72cca1c7b62cc25544e22ea1b42a4d7cfb7',
  1,
  2,
  10.448888888888888,
  '2015-08-29 13:55:19',
  372069],
 ['09d8afb81b161179b802853d9d1557802f1dc14830529b33c37d27976ba65f10',
  1,
  2,
  11.535398230088495,
  '2015-08-22 12:26:42',
  371013],
 ['7e987745a0b5b31b8c21b9c1e002580d786c7d25b4d887297dcb1cf623b7de82',
  1,
  2,
  11.508849557522124,
  '2015-08-20 13:34:55',
  370709],
 ['b127847647f2af588fb7638a44b8eb2605c16550f5096095aea1c006562d1589',
  1,
  2,
  12.546666666666667,
  '2015-08-16 12:19:34',
  370113],
 ['12425ab9db2078fc1e98790411ce5ff4ddc7f4dd26438873a2a7124ee280eebc',
  7,
  2,
  7.501875468867217,
  '2015-08-13 16:07:44',
  369724],
 ['c699490266e87b37ad3dcc8cbfe6b621cb0409497feaa93c5dfba43ff7311019',
  1,
  2,
  15.173333333333334,
  '2015-08-12 12:54:52',
  369554],
 ['84c1f77819ba4286c38da576d3f274b063a894badd49b0fb10b984c6d400aa7d',
  1,
  2,
  20.08888888888889,
  '2015-08-10 12:29:04',
  369245],
 ['ea01ddbd46418dfb627fc35042a60962d91b7a0bf0414045232937b6c7cd1972',
  1,
  2,
  20.0,
  '2015-08-03 12:35:54',
  368224],
 ['f44268f7dd0c4fa5f0c6a43a085ea511cb3b560f2651c84b76fbf230de3db0b5',
  2,
  2,
  22.78494623655914,
  '2015-07-31 13:29:45',
  367781],
 ['429f808e6a3c03f3d98427b233abc85d89858111fade96e20c89498fb1e4daf0',
  3,
  2,
  1.9230769230769231,
  '2015-07-29 22:26:28',
  367552],
 ['73dc39f5ee47ef51bde454057a3067c9f273c4368fafd5ea19a0939f507f3bbd',
  2,
  2,
  2.680965147453083,
  '2015-07-23 13:16:40',
  366593],
 ['1a0e39f9ba571a41e3dc7d721e904aa719aabe68d5367f89b5da4bf52e0e8ce7',
  1,
  2,
  4.444444444444445,
  '2015-07-21 13:10:32',
  366303],
 ['6fe80d1e87ac3a05c6be521ab31c3175359f5dbf01ac54d1fa9be2304ea4898e',
  6,
  1,
  17.84121320249777,
  '2015-07-18 17:10:47',
  365894],
 ['2b97eb1ebd3068d42a0abfaf17e4859afa4248b783d2bff176028edd47f04dc1',
  1,
  2,
  4.424778761061947,
  '2015-07-18 13:57:04',
  365872],
 ['d7b81ad8480afa954c88ab9df1437f59924ab3a8541874ce7c4fc2af6edcfac3',
  1,
  2,
  4.444444444444445,
  '2015-07-15 12:21:47',
  365423],
 ['2ebe9a9775da3eee8a933c6f35587788c93a57da2ca4a65f8163d917e5decac9',
  1,
  2,
  4.424778761061947,
  '2015-07-13 20:15:46',
  365180],
 ['eeb5f21cf8e8f757e46da62b94f70963977d16363d6b556760ff789c9d6ba4c1',
  1,
  2,
  137.78666666666666,
  '2015-07-09 16:25:55',
  364574],
 ['219c11509fcc443324570756a3f523c5eec3c02241d2284997023e9680d9ff54',
  1,
  2,
  4.444444444444445,
  '2015-07-04 12:37:37',
  363790],
 ['a954c0b0bb3966113bf592b85b44159162d82685edfa0c80d997572837f464f8',
  6,
  2,
  17.346053772766695,
  '2015-06-25 18:40:06',
  362525],
 ['7108af3989c06ac8f56f253f0e43fd9a1855b6cd6e483407c3fe31bbba26f98c',
  2,
  2,
  52.08064516129032,
  '2015-06-25 18:40:06',
  362525],
 ['75e9635e376be94b03593c548b673b25fe19960074870a0822fb44eb20af186d',
  1,
  2,
  4.424778761061947,
  '2015-06-24 12:57:46',
  362338],
 ['3b8677350bd458f6955054d0a25fa98019b95167c476f7930b3586f12848f559',
  2,
  2,
  2.6737967914438503,
  '2015-06-23 12:48:41',
  362172],
 ['77162de1e8ea682c70c2ac5e07dc64fbd5b14fad131bbeb3b9d78e7631a4cbdc',
  1,
  2,
  4.424778761061947,
  '2015-06-20 13:09:04',
  361764],
 ['77883d9e3b87d879410dd9cbf3c8eb5834822efdb24ce94b9af9a85c03137818',
  1,
  2,
  4.444444444444445,
  '2015-06-19 13:03:42',
  361630],
 ['6cc5393ee161dd5f8040490b514c12e90f07215a71c453844a7902536d9ad5e1',
  2,
  2,
  2.6737967914438503,
  '2015-06-17 13:31:38',
  361317],
 ['50283ef2ab8716eaae345aa000406d0ef80830b1cfbdacecb19e4911f0f53296',
  7,
  1,
  18.87355435620663,
  '2015-06-16 01:23:29',
  361126],
 ['070f4d5138c8ab0c1ca8b2d68e9a41d702e62ea0d44e278ef8f7edfd100b018b',
  1,
  2,
  44.44444444444444,
  '2015-06-12 18:02:26',
  360632],
 ['c73d29882fa31d46677bfb138e2dcf872a2960a1bf282b58bf3a98a5f1474387',
  5,
  2,
  20.512820512820515,
  '2015-06-10 02:36:23',
  360232],
 ['6383ba3284b914247fdde27e815be6c94a58a4edcce4849fd774213da2a9e382',
  6,
  2,
  10.40582726326743,
  '2015-06-04 13:07:24',
  359385],
 ['d03f12a6240ae0f965a230571407baf044f7873702db5c7eb474f7f4d5286e4a',
  2,
  2,
  26.737967914438503,
  '2015-06-03 22:23:35',
  359293],
 ['27a35771813ebdead3b8fd24954601f301406a50564aaa0c301f98e58469e5aa',
  1,
  2,
  4.424778761061947,
  '2015-05-28 11:34:35',
  358369],
 ['6d7ac92b1d2efcdf9df54162f8049dd8625f668008e861a62467b8ee790305ce',
  1,
  2,
  4.444444444444445,
  '2015-05-25 13:29:05',
  357971],
 ['2381a92e2dd43ba46516043163172b35ed064515ac703179bdbd078632361f80',
  1,
  2,
  44.24778761061947,
  '2015-05-21 13:42:11',
  357424],
 ['4eeb14e83d83dacc5e7c62409a0378152ddafd2140f61b138ceab90e4381d76b',
  1,
  2,
  4.444444444444445,
  '2015-05-19 12:20:43',
  357124],
 ['9568ba51fa10549eaa25ed688a1b85f918532d3f768ed73bd214781e115ee67d',
  1,
  2,
  44.44444444444444,
  '2015-05-15 12:40:44',
  356544],
 ['dc7f17d27b31417f5f43b090dc0e3e84e8887245a720fe920fe995a3ca3d152a',
  1,
  2,
  4.424778761061947,
  '2015-05-14 15:56:08',
  356406],
 ['175f54247749811da9755638a7c4c0613f553a3231addd4e09b4dba4029a21e1',
  1,
  2,
  44.44444444444444,
  '2015-05-11 12:21:11',
  355925],
 ['8db80c5828120be46f761b3bdedf2f575ff4e45eb97cf1aa8d51089df33b181c',
  24,
  2,
  2.281021897810219,
  '2015-05-07 04:07:44',
  355311],
 ['ea45008ec029782dd79161101e87dbdf68fa9211d0bdac2de548f7580b452673',
  1,
  2,
  44.24778761061947,
  '2015-05-05 13:37:56',
  355071],
 ['675a9b1d572da8d16bff3848c0ed5e7b8dec0a1292d8726709f583f19288cf49',
  1,
  2,
  4.424778761061947,
  '2015-05-04 13:21:29',
  354925],
 ['d0bebec0a54f984be2f03e2ab97053e79e6c2ca4c57e31a3f5e31e8cc4f06cac',
  1,
  2,
  44.642857142857146,
  '2015-05-01 11:35:43',
  354491],
 ['f42a9a887dd33844fb8103097875566314f58c80033ba820c3560c1c10b9b79e',
  1,
  2,
  44.44444444444444,
  '2015-04-28 10:35:15',
  354067],
 ['7604c9511ebacafb95f02fa94eb281f72c21826d3350aa3a2f0cb114512cd00b',
  1,
  2,
  44.24778761061947,
  '2015-04-27 12:21:02',
  353928],
 ['bd88ece6f2454b6d2905a2afc69d8ab52d35f42fd063f228e0182e9c6df07ec7',
  1,
  2,
  44.44444444444444,
  '2015-04-26 13:00:28',
  353795],
 ['435848d2a84d2ad9ae78372305b320e271668620d9f557b7609d65342059056c',
  1,
  2,
  4.424778761061947,
  '2015-04-24 12:01:43',
  353494],
 ['f96ce873cd63e98ac77781e3b491dd4b074c15c21cc15d0688745ae3c2ff83df',
  1,
  2,
  4.444444444444445,
  '2015-04-22 12:12:17',
  353225],
 ['6f7c279a031dde942d78461c770eeb075b64ea0e73945e955052460f3666d5e3',
  1,
  2,
  44.24778761061947,
  '2015-04-21 11:35:07',
  353081],
 ['94913fb13fcfa097a5418c18d8e5b59ce2c97356fed2a0cd508b350e6ae5a9d6',
  1,
  2,
  44.44444444444444,
  '2015-04-20 12:22:22',
  352918],
 ['3a6f28631844404ff19f7901f3ce4c8f345f3548620562af2030a236dbb18337',
  1,
  2,
  44.24778761061947,
  '2015-04-16 13:31:39',
  352371],
 ['3252da06f83da37f73cd46f7e95325c55678e255bd1a78506eea7d85d62fa507',
  1,
  2,
  44.44444444444444,
  '2015-04-13 12:33:05',
  351937],
 ['dcd2c1707fe70d18ca35e7f74cac2507679874595267b0ee01e1e64c3531c7a2',
  1,
  2,
  44.24778761061947,
  '2015-04-09 13:11:48',
  351387],
 ['7e51b2e8cc738a7434d186f40ba3bcdabed0f6a383d1b2d78011d543ae589d4b',
  1,
  2,
  4.444444444444445,
  '2015-04-07 12:51:38',
  351116],
 ['fec6dc610ebdc0002f2de11376397455de271f48cb775804a1966425be604036',
  1,
  2,
  4.424778761061947,
  '2015-04-02 11:25:38',
  350368],
 ['b2512c2f1b3ae9fe2a58e4ce19159b55fa31344224522e9dbac519808b068302',
  1,
  2,
  44.44444444444444,
  '2015-03-28 14:54:03',
  349661],
 ['06c138d7b6bdfaaac350a004cb950a24f071fb50247f9d7d61d0cff8ca351e4e',
  1,
  2,
  44.24778761061947,
  '2015-03-24 14:21:41',
  349023],
 ['e27935f449c1ed8de4e3a169b7f422a58edcad0573ac2d572057ce43000c9116',
  1,
  2,
  4.444444444444445,
  '2015-03-23 12:19:53',
  348837],
 ['258a73bef1e455925736447343f021e843f1e86f9a6af3fe96bb36c8f3b09cf4',
  1,
  2,
  44.24778761061947,
  '2015-03-21 13:48:46',
  348567],
 ['2cb5f581cfb85187731ae4538894f061b73153476f0c305d787a43304cd8f316',
  1,
  2,
  44.24778761061947,
  '2015-03-19 13:25:35',
  348281],
 ['730a4659321b635ffc39cf7ad0c84b80fc0e9c224e9981a83e6e4c6a8c29fa46',
  1,
  2,
  4.424778761061947,
  '2015-03-17 12:53:55',
  347994],
 ['f1560930060e84449d17c22d99d569d88e8a964a1b766d9418a5e26afe5088ba',
  1,
  2,
  4.424778761061947,
  '2015-03-14 13:32:10',
  347586],
 ['7037a8edcbe0c4a71e33112320e0e96001c5cfb646e6c3ca65999cdfc8d2b75a',
  1,
  2,
  221.23893805309734,
  '2015-03-14 12:55:16',
  347584],
 ['f9fbed6f05e58a04dedf97f57dd326e170cd80e087f24e71553cc9f1129c2461',
  5,
  2,
  20.491803278688526,
  '2015-03-14 03:34:17',
  347531],
 ['8a1c9a24874ba6533b822b44455e2bc4c9f4cab4189e70e0175569f684cc82e6',
  1,
  2,
  4.424778761061947,
  '2015-03-13 14:48:25',
  347448],
 ['a210d932403eac8f2a1be30922b13c210bdffac380655696edd4f165fa94bf3d',
  1,
  2,
  4.444444444444445,
  '2015-03-12 16:01:12',
  347317],
 ['3f0279d62fc82427a2220577b2e90bc8781922a4cdcd6eed60267d51aad7f56b',
  1,
  2,
  4.424778761061947,
  '2015-03-10 14:56:54',
  347017],
 ['97fd73e6e7d614c956daf33dd2ddf14d02cd30fb54d5fca252a45833a4652873',
  5,
  2,
  12.269938650306749,
  '2015-03-03 13:05:05',
  345993],
 ['02757148580b05c3921a793fe0dcd01f6ef61757e0ef25641ca22a273034bfac',
  6,
  2,
  8.658008658008658,
  '2015-02-28 13:24:26',
  345546],
 ['8519151ec79a0d000239fc4a5e211150e6a81ea1baee0d0b13a2ba7f98b14082',
  1,
  2,
  44.24778761061947,
  '2015-02-25 17:48:55',
  345126],
 ['4398dbad0d5babcb392201706cf6174a144396b0f8f82d22d64bb5956f78090f',
  1,
  2,
  44.24778761061947,
  '2015-02-22 16:58:22',
  344692],
 ['6c93dff61ac3c24a98cbbeede294d14d5ee4c66fa0b798ae6d305c8c43b73892',
  1,
  2,
  4.444444444444445,
  '2015-02-19 15:33:28',
  344233],
 ['33a727a3fc0f44dda077148c6ad2a75818a4e2ff536300e16e206cd438565b21',
  2,
  2,
  26.881720430107528,
  '2015-02-18 15:30:01',
  344060],
 ['25b7f3bf54ad21d1adb3cb272ae064490e6e67f8b74907fc56d770229cefd21c',
  2,
  2,
  22.727272727272727,
  '2015-02-15 20:17:08',
  343626],
 ['c69d4b0dfb0727a3ca3cf9a983410c39ef7ec5e72fcc8ca24b92165d87c44add',
  6,
  2,
  8.64304235090752,
  '2015-02-15 19:57:57',
  343625],
 ['2c2f0949486fc26ba0b94eba8029f9cb6853cccf2fe1f82d57aa4ba8b32c40ba',
  1,
  2,
  44.24778761061947,
  '2015-02-15 18:22:32',
  343609],
 ['349762484367ba41b0d499afaccf8afe5cf1cc12cdae4d1b2f9b9754322597ac',
  1,
  2,
  38.91050583657587,
  '2015-02-14 01:43:30',
  343355],
 ['96b015c421d096b5627b8ad814fe913c661d36f84b21cd2c3beaa726797ed7ad',
  2,
  2,
  22.779043280182233,
  '2015-02-14 00:17:42',
  343348],
 ['8baf93d7e8e57fd711e3b022ec443a95c84da9ec7e7df6e672067351d24aa882',
  1,
  2,
  38.91050583657587,
  '2015-02-14 00:17:42',
  343348],
 ['309682230e4709a8dd560b152987cefe0b1b128e6c9e438032dfbf47e9750ecb',
  1,
  2,
  38.91050583657587,
  '2015-02-14 00:17:42',
  343348],
 ['03fd531ccfe6d52d9905c9ebf1338fb541dd8f38c3dec7b4c90f6cb65ed11468',
  1,
  2,
  38.91050583657587,
  '2015-02-14 00:08:58',
  343347],
 ['337ba9a72aeffa0c159c032e8d0e97dde9ac15a82e9b76df79b13bf110b99ea2',
  2,
  2,
  22.988505747126435,
  '2015-02-14 00:08:58',
  343347],
 ['fae5e8f13bdb9955ca434e966a083f9ff032308a3560f5018bf4d07d1aab4591',
  2,
  2,
  22.88329519450801,
  '2015-02-14 00:08:58',
  343347],
 ['fac04b7c795f0eb319e0f070071de2e6d94f796977c4b6dcbd6152a81b13f123',
  1,
  2,
  44.44444444444444,
  '2015-02-13 17:48:11',
  343311],
 ['dd3f8789b326714cc46877fa886755c0b5c8c0e7490eb706fac2bff5599975a6',
  1,
  2,
  44.44444444444444,
  '2015-02-11 15:56:18',
  343024],
 ['a7049d60a3a86c5931ca4b6687435b5891bd1bff6a1102ec0974d2c62c623efe',
  7,
  2,
  14.970059880239521,
  '2015-02-10 12:27:05',
  342854],
 ['32101d37dc756be3834321e3db48c8c9b1486a09ce9ac442772b94d6c40f4121',
  1,
  2,
  222.22222222222223,
  '2015-02-09 18:39:20',
  342741],
 ['8530e71d306c312feffc00135adbf6db85f9376987e99e0564511f9616ead5fb',
  2,
  2,
  22.88329519450801,
  '2015-02-09 04:58:06',
  342655],
 ['7a1bf57f56b361031378d996beadb7ecdb455137f089362e7ca7feeee1f82141',
  2,
  2,
  22.88329519450801,
  '2015-02-09 04:45:29',
  342654],
 ['c71dd09e069ef0b3c081e669a13adc13790b44c3ba3e929296f3df0c611a6129',
  2,
  2,
  22.88329519450801,
  '2015-02-07 22:13:07',
  342475],
 ['9665b601763910afe1bf74d6a683aebf477539002199686c8a4bc2ff559e9f83',
  2,
  2,
  22.831050228310502,
  '2015-02-07 22:05:14',
  342473],
 ['5da54c5579f2e3548507c4713f57c9537e63f0992333343972b7b26890dfae96',
  2,
  2,
  22.831050228310502,
  '2015-02-07 22:05:14',
  342473],
 ['9a060f62d40bc4e3e320d77e2a811ed3608bb5566790bc31e5978e32bcb3dbe5',
  3,
  2,
  16.207455429497568,
  '2015-02-07 21:28:19',
  342471],
 ['24ed424a8eb588872f03d03e177c7697f93c73ab0a3240389b62e24e1ac02397',
  2,
  2,
  22.831050228310502,
  '2015-02-07 15:23:21',
  342430],
 ['457708002c88401fd763e1de9223a1dfe924c1e4261651afddd07e1c3fab98f2',
  1,
  2,
  38.75968992248062,
  '2015-02-07 15:20:33',
  342429],
 ['cf09e4a726560da93b43f0e8d13c704f30fcdc88cd58c432dd01c5ab4ff4600f',
  1,
  2,
  38.75968992248062,
  '2015-02-07 15:20:33',
  342429],
 ['af4f5e2ddee23e8de7a2910601d0af9be23e066268ddb13b2ab215d057a67bda',
  1,
  2,
  38.75968992248062,
  '2015-02-07 15:20:33',
  342429],
 ['d95844b09436fb84399e936d89d807ac678f16608e9305ae088b6b817fc47a4f',
  2,
  2,
  22.727272727272727,
  '2015-02-07 14:41:11',
  342426],
 ['9a9394e44829ad0cfe8d63fcde3387e6edc84876a446fc0fa11714d91412e2fe',
  1,
  2,
  38.91050583657587,
  '2015-02-07 14:36:16',
  342425],
 ['ab1fec5fa06a667e78d097a5e68eb3b19aa70b52e47b5b504319fddc0efd9daf',
  2,
  2,
  22.88329519450801,
  '2015-02-06 21:36:39',
  342309],
 ['a4b911b993628b4575eea7135bd0a3ce8a2a4c8017ed4b76af5d9eff3d2bb71d',
  1,
  2,
  38.75968992248062,
  '2015-02-06 21:36:39',
  342309],
 ['dc45a2cea9e3316872eb18f1f71ca45ec088495f203d2103a08d43c18c3f6c58',
  2,
  2,
  22.88329519450801,
  '2015-02-06 21:10:04',
  342307],
 ['3ad792b3d6f0e94ab49fe17a4b5f2ba808494cb1b2bde890baeba66f5f9d778a',
  1,
  2,
  38.91050583657587,
  '2015-02-06 21:10:04',
  342307],
 ['c56dd046a5c1cb7df6e0a932deb7fea26af9a0a23683aea4a7b58a9d48eeba59',
  1,
  2,
  4.424778761061947,
  '2015-02-06 17:47:44',
  342276],
 ['27d5de71a3b7e285240a56da33d0ac1f172a008bed0b46a59bf6a71831f9181b',
  1,
  2,
  44.24778761061947,
  '2015-02-05 18:07:43',
  342107],
 ['e396cc00fc94c278d72d2885ec18b6c696c2cebb775f496281c100516bff9854',
  1,
  2,
  44.44444444444444,
  '2015-02-03 15:54:01',
  341787],
 ['fe98723ccf348714f3bc1d3e5689114a27f4edee96722772be9db0bf02a6625c',
  6,
  2,
  17.301038062283737,
  '2015-02-01 06:19:47',
  341436],
 ['39dd458c020ed6f03715393d5410b5c8d183880961cf70bba27dc10e73d02ea3',
  2,
  2,
  26.80965147453083,
  '2015-01-29 19:47:29',
  341061],
 ['5bbbdf0fdd72aba4a4c2cb78e4498dd32b5e5c9dee89a48f4cdcb3215cfe9173',
  1,
  2,
  44.44444444444444,
  '2015-01-28 17:36:41',
  340877],
 ['b9b36d4e6d7a6bfd4b06fa799d315c75df389fcd92d5e7bb30777bff8653aba7',
  2,
  2,
  26.80965147453083,
  '2015-01-27 21:35:17',
  340745],
 ['40a6ca6863420a5882347fee3aa784fc8d4e1dd6324add72ce5cf99693658df5',
  1,
  2,
  44.44444444444444,
  '2015-01-25 17:39:07',
  340450],
 ['79d36355c316e99e28b044fc872181da5f708b4b925dcb9e8c77157a3d81a455',
  1,
  2,
  4.424778761061947,
  '2015-01-24 16:51:49',
  340321],
 ['6eec1e8e12c9c9555acd064be783038c749be83c47f8ee881d755e3e5cc4211b',
  2,
  2,
  22.93577981651376,
  '2015-01-24 08:49:55',
  340282],
 ['af10c797acfebfca955d616fc2559d32cbff39b00efd6f497b030e7d0d0d863f',
  1,
  2,
  44.44444444444444,
  '2015-01-21 15:50:32',
  339914],
 ['2cd8bfd8f06d5e45cc2e9f5f5b38baed1cc244fbe87ef0d0b042b0e4eb5ab342',
  2,
  2,
  22.988505747126435,

In [10]:
address = "bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd"
url = f"https://blockchain.info/rawaddr/{address}"
r = requests.get(url)
r = r.json()
r

{'hash160': None,
 'address': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd',
 'n_tx': 4,
 'n_unredeemed': 1,
 'total_received': 27063,
 'total_sent': 17063,
 'final_balance': 10000,
 'txs': [{'hash': 'c1a69100367d47ee9db89d935a49510459132363cb5c63471777cd44682d4561',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 3,
   'size': 265,
   'weight': 733,
   'fee': 520,
   'relayed_by': '0.0.0.0',
   'lock_time': 961196,
   'tx_index': 3422391758264750,
   'double_spend': False,
   'time': 1785957393,
   'block_index': 961197,
   'block_height': 961197,
   'inputs': [{'sequence': 4294967293,
     'witness': '024730440220399538385cb942096d69f0317a754c803aa095f9f913c07771ed73851904b16b02200efcc98c22d88310529a19352c0778323430d5b4e03ef3842dfafca54590473c012103cad95529ce8b6b25cf76f39d882d5a4c6446aa51ffa58226fa27ab77f0b07e23',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 22720,
      'spending_outpoints': [{'tx_index': 3422391758264750, 'n': 0}],
      'n': 0,
      'tx_index': 4907916439945834,
      'script': '0014bb634e432999dd762d152e18290e70f4b1135e94',
      'addr': 'bc1qhd35usefn8whvtg49cvzjrns7jc3xh55588zj0'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 2200,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 3422391758264750,
     'script': '0014f4990c18861cc0389628f9bd5e690aa71d70629a',
     'addr': 'bc1q7jvscxyxrnqr393glx74u6g25uwhqc56aakalf'},
    {'type': 0,
     'spent': False,
     'value': 10000,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 3422391758264750,
     'script': '0014f27a21ba92520510d82da6d629534a6710b29c5a',
     'addr': 'bc1q7fazrw5j2gz3pkpd5mtzj562vugt98z6h20xn7'},
    {'type': 0,
     'spent': False,
     'value': 10000,
     'spending_outpoints': [],
     'n': 2,
     'tx_index': 3422391758264750,
     'script': '5120171bdab208e800c99016ebe9b0f5c7965df9ee51416890d49eb5ca785032111a',
     'addr': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd'}],
   'result': 10000,
   'balance': 10000},
  {'hash': '0530871080f2c50146136e6c4ed2880b3368fec585363dfb465713ecbfca7d8b',
   'ver': 1,
   'vin_sz': 4,
   'vout_sz': 1,
   'size': 475,
   'weight': 1090,
   'fee': 1643,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 4907916439945834,
   'double_spend': False,
   'time': 1785952870,
   'block_index': 961192,
   'block_height': 961192,
   'inputs': [{'sequence': 4294967295,
     'witness': '0141645454ca739c4c03488d81bd27bee26009263f8aa8f36bd0600528cd5134c8b1b6e32d66af5e2639252eea81d4c4e52cb2d5be109b4959f8edb7839518f86ff801',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 2300,
      'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 0}],
      'n': 0,
      'tx_index': 6880886329382641,
      'script': '512083a5e44247777294d0c6299e6c21c8379633b34d50e2ad760297422d036a48fd',
      'addr': 'bc1pswj7gsj8waeff5xx9x0xcgwgx7tr8v6d2r326aszjapz6qm2fr7sswmxjc'}},
    {'sequence': 4294967295,
     'witness': '0141cbd80dd23318dfc3db9b36019220684aa4306bf145897276888bdab0d9c5efe0f10bfd11ca32dec59b0d576b3f47b38abde335b4dde766f25aae15bcc00d649e01',
     'script': '',
     'index': 1,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 11963,
      'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 1}],
      'n': 0,
      'tx_index': 184246007991223,
      'script': '5120171bdab208e800c99016ebe9b0f5c7965df9ee51416890d49eb5ca785032111a',
      'addr': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd'}},
    {'sequence': 4294967295,
     'witness': '0141edf53287dd64fff766498579eb70d62d479ba6ca5e5bd87e36f0643393420050a8ccaab4944518f1e29d2b0f66e0b3b55b077a6c12dfb825cf4146cb7bb90f4501',
     'script': '',
     'index': 2,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 5000,
      'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 2}],
      'n': 0,
      'tx_index': 2268494631655913,
      'script': '51201aa2e92b0bf8b62b8b3982b39e43c4ca80db786524fc06993e9c890f1e087e4f',
      'addr': 'bc1pr23wj2ctlzmzhzees2eeus7ye2qdk7r9yn7qdxf7njys78sg0e8ssx0mzf'}},
    {'sequence': 4294967295,
     'witness': '01419f8fae4b81a621ad9191c10a6ad34ec07c16d66bf5f9e5fb0b029fbd3543b86dd1288a59505f2eaed970782afffb23e83f7583d86f10531b6d067b165dda96a001',
     'script': '',
     'index': 3,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 5100,
      'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 3}],
      'n': 0,
      'tx_index': 2692229090724059,
      'script': '5120171bdab208e800c99016ebe9b0f5c7965df9ee51416890d49eb5ca785032111a',
      'addr': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd'}}],
   'out': [{'type': 0,
     'spent': True,
     'value': 22720,
     'spending_outpoints': [{'tx_index': 3422391758264750, 'n': 0}],
     'n': 0,
     'tx_index': 4907916439945834,
     'script': '0014bb634e432999dd762d152e18290e70f4b1135e94',
     'addr': 'bc1qhd35usefn8whvtg49cvzjrns7jc3xh55588zj0'}],
   'result': -17063,
   'balance': 0},
  {'hash': 'af72ec1bff288d14cd3d476cee8d352face9a66a79adc81aa3ba5ddcee903c05',
   'ver': 2,
   'vin_sz': 5,
   'vout_sz': 1,
   'size': 795,
   'weight': 1569,
   'fee': 393,
   'relayed_by': '0.0.0.0',
   'lock_time': 943961,
   'tx_index': 184246007991223,
   'double_spend': False,
   'time': 1775511694,
   'block_index': 943963,
   'block_height': 943963,
   'inputs': [{'sequence': 4294967293,
     'witness': '0247304402205a11a3686c25e6a4e46790b30061a533e15179fb0dfb57560196b4008ca2391c0220038cbb21de18458db9314fbb83c29e6da9294918ced0421c3f075bd43ff47603012103f09970f5c7513d00c86c7172e352c00a7df7807cc73fa5faadf00e4ac34074c5',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 2000,
      'spending_outpoints': [{'tx_index': 184246007991223, 'n': 0}],
      'n': 0,
      'tx_index': 4971645243983326,
      'script': '0014f27a21ba92520510d82da6d629534a6710b29c5a',
      'addr': 'bc1q7fazrw5j2gz3pkpd5mtzj562vugt98z6h20xn7'}},
    {'sequence': 4294967293,
     'witness': '024730440220241aa20685e039b04228256e5041e39cc05a958f2b03244115093a1d92182f7b022025a49bd59ca3d67dcc43c048f09439bb40cbcd4521b29e55e059e4376f8bda230121025df6ed83199440415af4c969ebb5c6475ff92d0d61028092e09cf482732f3d45',
     'script': '',
     'index': 1,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 2500,
      'spending_outpoints': [{'tx_index': 184246007991223, 'n': 1}],
      'n': 0,
      'tx_index': 5903112089802222,
      'script': '001462c86ed2471c492fd16f0e93717bef0f2aea9e3c',
      'addr': 'bc1qvtyxa5j8r3yjl5t0p6fhz7l0pu4w483ulfnuj7'}},
    {'sequence': 4294967293,
     'witness': '024730440220598c45dbf2d66832167d6b06aa89cb07e3561b563118846a9b422e59f71f3cdf02202b5cda5ee9343f3746c8f3e93d5c7dcbb9a57256ec1ea42d6fc9b631d35ca2a1012103f09970f5c7513d00c86c7172e352c00a7df7807cc73fa5faadf00e4ac34074c5',
     'script': '',
     'index': 2,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 4000,
      'spending_outpoints': [{'tx_index': 184246007991223, 'n': 2}],
      'n': 1,
      'tx_index': 2983255035588985,
      'script': '0014f27a21ba92520510d82da6d629534a6710b29c5a',
      'addr': 'bc1q7fazrw5j2gz3pkpd5mtzj562vugt98z6h20xn7'}},
    {'sequence': 4294967293,
     'witness': '02473044022072ceba54dee64b5f0b093502f58917b9b5e0034b8ca3fa59a73a5e97f2f2869702201bac31a602cf03130d348bd336d3455e992ee5e2974515bf5d50b07f34f54938012103f09970f5c7513d00c86c7172e352c00a7df7807cc73fa5faadf00e4ac34074c5',
     'script': '',
     'index': 3,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 2000,
      'spending_outpoints': [{'tx_index': 184246007991223, 'n': 3}],
      'n': 0,
      'tx_index': 2992996041541968,
      'script': '0014f27a21ba92520510d82da6d629534a6710b29c5a',
      'addr': 'bc1q7fazrw5j2gz3pkpd5mtzj562vugt98z6h20xn7'}},
    {'sequence': 4294967293,
     'witness': '0247304402203979df27874aeacf2fed63a0d29d49e054b851d913ea858216b691fac9a99fdb02203cf22fa14d4c10cab622c333299ccf7d7fdf5900e6d031a659f95ab0aac52e60012103eee8fbab7d20513d851e35ea1d6e21975ac72c7bee289ba607acf234ef391385',
     'script': '',
     'index': 4,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 1856,
      'spending_outpoints': [{'tx_index': 184246007991223, 'n': 4}],
      'n': 1,
      'tx_index': 6541334703190959,
      'script': '001461a6c045fcd3af72f0a8d38d5391f9502c74a817',
      'addr': 'bc1qvxnvq30u6whh9u9g6wx48y0e2qk8f2qhyremyw'}}],
   'out': [{'type': 0,
     'spent': True,
     'value': 11963,
     'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 1}],
     'n': 0,
     'tx_index': 184246007991223,
     'script': '5120171bdab208e800c99016ebe9b0f5c7965df9ee51416890d49eb5ca785032111a',
     'addr': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd'}],
   'result': 11963,
   'balance': 17063},
  {'hash': '8a02bb1faaaade3df1f48c9e67ee736ee2f17ba209e44b7dd8df46da748b844c',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 1,
   'size': 203,
   'weight': 485,
   'fee': 200,
   'relayed_by': '0.0.0.0',
   'lock_time': 943961,
   'tx_index': 2692229090724059,
   'double_spend': False,
   'time': 1775511487,
   'block_index': 943962,
   'block_height': 943962,
   'inputs': [{'sequence': 4294967293,
     'witness': '0247304402205e2e62c652411b152e1c3316110825e0dfd3f2b42395820cd4d2500999c726dd022006822a7965b4b19db056f1767fc696275f41a07dd7ccce6e61d71afbf92a5ce5012102f926fa877a38b65d0b68f30fd5e823f4d95964301cb1061f54f9bfa390d36118',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 5300,
      'spending_outpoints': [{'tx_index': 2692229090724059, 'n': 0}],
      'n': 1,
      'tx_index': 2268494631655913,
      'script': '00143536cc2d23927015a5e80a1f35ab944346bd8afc',
      'addr': 'bc1qx5mvctfrjfcptf0gpg0nt2u5gdrtmzhuqv0qcp'}}],
   'out': [{'type': 0,
     'spent': True,
     'value': 5100,
     'spending_outpoints': [{'tx_index': 4907916439945834, 'n': 3}],
     'n': 0,
     'tx_index': 2692229090724059,
     'script': '5120171bdab208e800c99016ebe9b0f5c7965df9ee51416890d49eb5ca785032111a',
     'addr': 'bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh98s5pjzydqme8dwd'}],
   'result': 5100,
   'balance': 5100}]}

In [44]:
#Blockchain data creation
data = pd.DataFrame(r["txs"])

blockchain_data = pd.DataFrame()
blockchain_data["txid"] = data["hash"]
blockchain_data["num_inputs"] = data["vin_sz"]
blockchain_data["num_outputs"] = data["vout_sz"]
blockchain_data["fee"] = data["fee"]/data["size"]
blockchain_data["mempool_entry_time"] = pd.to_datetime(
        data['time'], 
        unit='s',       
        utc=True        
    ).dt.strftime("%Y-%m-%d %H:%M:%S")
blockchain_data["block_height"] = data["block_height"]

In [43]:
#Tx inputs table data creation
df_inputs = data[['hash', 'inputs']].explode('inputs').dropna(subset=['inputs'])
df_inputs = df_inputs.reset_index(drop=True)
inputs_expanded = pd.DataFrame(df_inputs['inputs'].tolist())
inputs_df = df_inputs[['hash']].join(inputs_expanded).reset_index(drop=True)
inputs_df["prev_out"] = inputs_df['prev_out'].to_dict()
df = pd.DataFrame(inputs_df["prev_out"].tolist(), index = inputs_df.index)
final_inputs = pd.concat([inputs_df, df], axis = 1)

tx_inputs = pd.DataFrame()
tx_inputs["txid"] = final_inputs["hash"]
tx_inputs["input_order"] = final_inputs["index"]
tx_inputs["address"] = final_inputs["addr"]
tx_inputs["value"] = final_inputs["value"]/100000000

In [48]:
#Tx outputs table data creation
df_outputs = data[['hash', 'out']].explode('out').dropna(subset=['out'])
df_outputs = df_outputs.reset_index(drop=True)
outputs_expanded = pd.DataFrame(df_outputs['out'].tolist())
outputs_df = df_outputs[['hash']].join(outputs_expanded).reset_index(drop=True)

tx_outputs = pd.DataFrame()
tx_outputs["txid"] = outputs_df["hash"]
tx_outputs["output_order"] = outputs_df["n"]
tx_outputs["address"] = outputs_df["addr"]
tx_outputs["value"] = outputs_df["value"]/100000000
tx_outputs

,txid,output_order,address,value
0,c1a69100367d47ee9db89d935a49510459132363cb5c63...,0,bc1q7jvscxyxrnqr393glx74u6g25uwhqc56aakalf,0.000022
1,c1a69100367d47ee9db89d935a49510459132363cb5c63...,1,bc1q7fazrw5j2gz3pkpd5mtzj562vugt98z6h20xn7,0.000100
2,c1a69100367d47ee9db89d935a49510459132363cb5c63...,2,bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh...,0.000100
3,0530871080f2c50146136e6c4ed2880b3368fec585363d...,0,bc1qhd35usefn8whvtg49cvzjrns7jc3xh55588zj0,0.000227
4,af72ec1bff288d14cd3d476cee8d352face9a66a79adc8...,0,bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh...,0.000120
5,8a02bb1faaaade3df1f48c9e67ee736ee2f17ba209e44b...,0,bc1pzuda4vsgaqqvnyqka05mpaw8jewlnmj3g95fp4y7kh...,0.000051